### ISSUE TITLE
Provided stream substitution in runAndTest() resulting in NullPointerException or OutOfMemoryError

### ISSUE THREAD

**Issue by rykrr** [CISC-CMPE-327/CI-Java-Maven#1]
The console class below wraps around a buffered reader to handle all terminal inputs. There is typically only one (1) console per program. This works perfectly for individual program runs. However, when called from runAndTest(), the reader returns the first element specified in terminal_input[] and returns null in all subsequent calls.

```
// The Input wrapper class
public Console() {
    if(reader == null)
        reader = new BufferedReader(new InputStreamReader(System.in));
}

//read the next line of console input
public String readString() {
    try {
        return reader.readLine();
    } catch (IOException e) {
	e.printStackTrace();
        return "";
    }
}
```

To get around this issue, we created a FakeConsole class that runs on a list of inputs.

```
private List<String> inputs;

public FakeConsole(List<String> inputs) {
    this.inputs = new ArrayList<>(inputs);
}

public String readString() {
    if(inputs.isEmpty())
        return "";
    return inputs.remove(0);
}
```

Past this point, a new error emerges regarding the output stream:
```
java.lang.OutOfMemoryError: Java heap space

	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
	at java.base/java.io.PrintStream.write(PrintStream.java:559)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
	at java.base/java.io.PrintStream.newLine(PrintStream.java:625)
	at java.base/java.io.PrintStream.println(PrintStream.java:883)
	at ca.queensu.cisc327.afk.Main.<init>(Main.java:48)
	at ca.queensu.cisc327.afk.Main.fakeMain(Main.java:30)
	at ca.queensu.cisc327.afk.AppTest.runAndTest(AppTest.java:88)
	at ca.queensu.cisc327.afk.AppTest.testAppR1(AppTest.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

```

If anyone has any suggestions, please let us know. We are considering switching to the C/C++ testing approach.

**Comment by rykrr** [comment]
[Link to test directory](https://github.com/rykrr/Quinterac/tree/jUnit/prototype/src/test/java/ca/queensu/cisc327/afk)

**Comment by steven-hh-ding** [comment]
Hey Ryan. Can you use the Scanner API in console instead?

**Comment by rykrr** [comment]
Hello Professor,
It appears using a scanner does appear to work (even after multiple runs of the same test!).
Thank you!

**Comment by steven-hh-ding** [comment]
good luck. ping me if there is any problem.
